[build]
  # Статический сайт — сборка не нужна
  command = "echo 'no build step'"
  # Публикуем директорию, где лежит index.html
  publish = "FroggyHub"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg","bcryptjs","jsonwebtoken"]
  directory = "netlify/functions"
